services:
  paper:
    image: itzg/minecraft-server:java21
    container_name: dynamic-biomes-paper
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.4"
    ports:
      - "25566:25566"
    volumes:
      - ./server-data:/data:Z
      - ../java/app/build/libs:/plugins-src:ro
